LCode.InfraestruCode.Cliente/Controllers/HomeController.cs
using LCode.InfraestruCode.Cliente.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LCode.InfraestruCode.Cliente.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LCode.InfraestruCode.Cliente/Controllers/SesionController.cs
using BCP.NETCore.Base;
using LCode.InfraestruCode.Cliente.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using NETCore.Base._3._0;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace LCode.InfraestruCode.Cliente.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SesionController : ControllerBase
    {
        private List<string> ObtenerRoles(System.DirectoryServices.ResultPropertyValueCollection Grupos)
        {
            List<string> Roles = new List<string>();
            bool Desarrollo = DirectorioActivo.ValidacionGrupo(Grupos, "DESARROLLO");
            if (Desarrollo)
            {
                Roles.Add("Usuario-Desarrollo");
            }
            bool Certificacion = DirectorioActivo.ValidacionGrupo(Grupos, "CERTIFICACION");
            if (Certificacion)
            {
                Roles.Add("Usuario-Certificacion");
            }
            bool ServidoresMonitoreo = DirectorioActivo.ValidacionGrupo(Grupos, "GDMonitoreo");
            if (ServidoresMonitoreo)
            {
                Roles.Add("Admin");
            }
            return Roles;
        }
        // POST api/<SesionAController>
        [HttpPost]
        public IActionResult Post([FromBody] Sesion value)
        {
            try
            {
                BaseConfiguracion BC = new BaseConfiguracion();
                string Llave = BC.ObtenerValor("SecretKey");
                var key = Base64UrlEncoder.DecodeBytes(Llave);
                try
                {
                    DirectorioActivo DA = new DirectorioActivo();
                    if (DA.ValidarUsrContrasena(value.Usuario, value.Contrasenia))
                    {
                        var One = DA.ObtenerInformacion(value.Usuario, value.Contrasenia);
                        var Roles=ObtenerRoles(One.Properties["memberof"]);
                        if (Roles.Count>0)
                        { 
                            //DatosSesion Datos = new DatosSesion();
                            //Datos.Usuario = One.Properties["samaccountname"][0].ToString();
                            //Datos.Nombres = One.Properties["givenname"][0].ToString();
                            //Datos.Apellidos = One.Properties["sn"][0].ToString();
                            //Datos.Correo = One.Properties["userprincipalname"][0].ToString();
                            string guidsesion = Guid.NewGuid().ToString();
                            var claims = new ClaimsIdentity(new[]
                            {
                                new Claim(ClaimTypes.Name, One.Properties["givenname"][0].ToString()),
                                new Claim(ClaimTypes.Surname, One.Properties["sn"][0].ToString()),
                                new Claim(ClaimTypes.WindowsUserClaim, One.Properties["samaccountname"][0].ToString()),
                                new Claim(ClaimTypes.Email, One.Properties["userprincipalname"][0].ToString()),
                                new Claim(ClaimTypes.Sid, guidsesion),
                                new Claim(ClaimTypes.PrimarySid, guidsesion+";"+value.Usuario),
                            });
                            foreach (string Rol in Roles)
                            {
                                claims.AddClaim(new Claim(ClaimTypes.Role, Rol));
                            }
                            var tokenDescriptor = new SecurityTokenDescriptor
                            {
                                Subject = claims,
                                Expires = DateTime.UtcNow.AddMinutes(60),
                                SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha256)
                            };

                            var tokenHandler = new JwtSecurityTokenHandler();
                            var createdToken = tokenHandler.CreateToken(tokenDescriptor);
                            string token = tokenHandler.WriteToken(createdToken);
                            Response.Cookies.Append("token", token);
                            return Ok(JsonConvert.SerializeObject(token));
                        }
                        else
                        {
                            return Unauthorized();
                        }
                    }
                    else
                    {
                        return Unauthorized();
                    }
                }
                catch (Exception Ex)
                {
                    return StatusCode(500);
                }
            }
            catch
            {
                return StatusCode(500);
            }
        }
        //public string Generate()
        //{
        //    List<Claim> claims = new List<Claim>() {
        //    new Claim (JwtRegisteredClaimNames.Jti,
        //        Guid.NewGuid().ToString()),

        //    new Claim (JwtRegisteredClaimNames.Email,
        //        user.EmailAddress),

        //    new Claim (JwtRegisteredClaimNames.Sub,
        //        user.Id.ToString()),
		    
        //    // Add the ClaimType Role which carries the Role of the user
        //    new Claim (ClaimTypes.Role, user.Role)
        //    };

        //    JwtSecurityToken token = new TokenBuilder()
        //        .AddAudience(TokenConstants.Audience)
        //        .AddIssuer(TokenConstants.Issuer)
        //        .AddExpiry(TokenConstants.ExpiryInMinutes)
        //        .AddKey(TokenConstants.key)
        //        .AddClaims(claims)
        //        .Build();

        //    string accessToken = new JwtSecurityTokenHandler()
        //        .WriteToken(token);

        //    return accessToken;
        //}

    }
}

LCode.InfraestruCode.Cliente/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container my-5 py-5 z-depth-1">
    @*<h1 class="display-4">Bienvenid@@</h1>*@
    @if (!User.Identity.IsAuthenticated)
    {
        <section class="px-md-5 mx-md-5 text-center dark-grey-text">

            <!--Grid row-->
            <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-4 mb-md-0">

                    <h3 class="font-weight-bold text-primary">Inicia Sesión!</h3>

                    <p class="text-muted">
                        <i class="fas fa-file-invoice fa-2x text-warning"></i>
                        Ingresa tus credenciales de dominio en el siguiente formulario!
                    </p>
                    @*<form asp-action="InicioSesion" asp-controller="Sesion">*@
                    <div class="md-form" style="text-align: left!important;">
                        <i class="fas fa-user prefix blue-text"></i>
                        <input type="text" id="Usuario" class="form-control">
                        <label for="Usuario">Nombre Usuario de Dominio</label>
                    </div>
                    <div class="md-form" style="text-align: left!important;">
                        <i class="fas fa-lock prefix blue-text"></i>
                        <input type="password" id="Contrasenia" class="form-control">
                        <label for="Contrasenia">Contraseña</label>
                    </div>

                    <div class="text-center">
                        <button id="login" class="btn btn-outline-success btn-rounded waves-effect">Iniciar Sesion</button>
                        @*<input type="submit" value="Iniciar Sesion" class="btn btn-outline-success btn-rounded waves-effect" />*@
                    </div>
                    @*</form>*@
                    <!--<hr class="my-5">

                    <p class="font-weight-bold">Síguenos en nuestras redes sociales:</p>-->
                    <!--Facebook-->
                    <!--<a href="https://www.facebook.com/medico.com.bo" class="mx-1" role="button"><i class="fab fa-facebook-f"></i></a>
                    <a href="https://www.linkedin.com/company/tercer-elemento" class="mx-1" role="button"><i class="fab fa-linkedin-in"></i></a>-->

                </div>
                <!--Grid column-->
                <!--Grid column-->
                <div class="col-md-5 mb-4 mb-md-0">

                    <img src="/img/serverlogin.jpg" class="img-fluid" alt="">

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->


        </section>
    }
    else
    {
        <h1 class="display-4">Bienvenid@@ @User.Claims.FirstOrDefault(x=>x.Type== System.Security.Claims.ClaimTypes.Name).Value</h1>
    }
    @*<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>*@
</div>
@section Scripts {
    <script type="text/javascript" src="~/js/Sitio/Login.js"></script>
}