LCode.InfraestruCode.Cliente/Controllers/ServidoresSolicitudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LCode.InfraestruCode.Core.BD.Contexto.v1_0;
using LCode.InfraestruCode.Core.BD.Contexto.v1_0.Modelos;
using Microsoft.AspNetCore.Authorization;
using NETCore.Base._3._0;

namespace LCode.InfraestruCode.Cliente.Controllers
{
    public class ServidoresSolicitudController : Controller
    {
        private readonly LCODEContexto _context= new LCODEContexto();

        // GET: ServidoresSolicitud
        [Authorize(Roles = "Admin,Usuario-Desarrollo")]
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Admin")) { 
                return View(await _context.SolicitudesServidores.Where(x=>x.Servidor.StartsWith("DEV")).ToListAsync());
            }
            else
            {
                return View(await _context.SolicitudesServidores.Where(x=>x.UsuarioSolicita==(User.Claims.FirstOrDefault(x => x.Type == System.Security.Claims.ClaimTypes.WindowsUserClaim).Value) && x.Servidor.StartsWith("DEV")).ToListAsync());
            }
        }

        [Authorize(Roles = "Admin,Usuario-Certificacion")]
        public async Task<IActionResult> IndexCertificacion()
        {
            if (User.IsInRole("Admin"))
            {
                return View(await _context.SolicitudesServidores.Where(x => x.Servidor.StartsWith("CER")).ToListAsync());
            }
            else
            {
                return View(await _context.SolicitudesServidores.Where(x => x.UsuarioSolicita == (User.Claims.FirstOrDefault(x => x.Type == System.Security.Claims.ClaimTypes.WindowsUserClaim).Value) && x.Servidor.StartsWith("CER")).ToListAsync());
            }
        }

        // GET: ServidoresSolicitud/Details/5
        [Authorize(Roles = "Admin,Usuario-Desarrollo,Usuario-Certificacion")]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var servidoresSolicitud = await _context.SolicitudesServidores
                .FirstOrDefaultAsync(m => m.GuidSolicitud == id);
            if (servidoresSolicitud == null)
            {
                return NotFound();
            }

            return View(servidoresSolicitud);
        }
        [Authorize(Roles = "Admin,Usuario-Desarrollo")]
        // GET: ServidoresSolicitud/Create
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin,Usuario-Certificacion")]
        // GET: ServidoresSolicitud/Create
        public IActionResult CreateCertificacion()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Usuario-Certificacion")]
        public async Task<IActionResult> CreateCertificacion([Bind("Servidor,TipoSolicitud,Observacion")] ServidoresSolicitud servidoresSolicitud)
        {
            if (ModelState.IsValid)
            {
                BaseConfiguracion BC = new BaseConfiguracion();
                Guid guid = Guid.NewGuid();
                servidoresSolicitud.GuidSolicitud = guid.ToString();
                servidoresSolicitud.Servidor = "CER" + servidoresSolicitud.Servidor.ToUpper();
                servidoresSolicitud.FechaHoraRegistro = DateTime.Now;
                servidoresSolicitud.FechaHoraUltimaModificacion = DateTime.Now;
                servidoresSolicitud.EstadoSolicitud = EstadoSolicitud.Solicitud_Iniciada;
                servidoresSolicitud.UsuarioSolicita = User.Claims.FirstOrDefault(x => x.Type == System.Security.Claims.ClaimTypes.WindowsUserClaim).Value;
                _context.Add(servidoresSolicitud);
                _context.SaveChanges();
                Api api = new Api();
                string MQResp = api.Post(BC.ObtenerValor("URL:SolicitudServidoresMQ"), servidoresSolicitud);
                if (MQResp != null)
                {
                    return Redirect("/ServidoresSolicitud/Details/" + servidoresSolicitud.GuidSolicitud);
                }
                else
                {
                    servidoresSolicitud.Mensaje = "Ha ocurrido un error con el servicio de ejecución, reporte al administrador!";
                    servidoresSolicitud.FechaHoraUltimaModificacion = DateTime.Now;
                    servidoresSolicitud.EstadoSolicitud = EstadoSolicitud.Solicitud_Error;
                    _context.Entry(servidoresSolicitud).State = EntityState.Modified;
                    _context.SaveChanges();
                    return RedirectToAction("500", "Error");
                }
            }
            return View(servidoresSolicitud);
        }
        // POST: ServidoresSolicitud/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Usuario-Desarrollo")]
        public async Task<IActionResult> Create([Bind("Servidor,TipoSolicitud,Observacion")] ServidoresSolicitud servidoresSolicitud)
        {
            if (ModelState.IsValid)
            {
                BaseConfiguracion BC = new BaseConfiguracion();
                Guid guid = Guid.NewGuid(); 
                servidoresSolicitud.GuidSolicitud = guid.ToString();
                servidoresSolicitud.Servidor = "DEV"+servidoresSolicitud.Servidor.ToUpper();
                servidoresSolicitud.FechaHoraRegistro = DateTime.Now;
                servidoresSolicitud.FechaHoraUltimaModificacion = DateTime.Now;
                servidoresSolicitud.EstadoSolicitud = EstadoSolicitud.Solicitud_Iniciada;
                servidoresSolicitud.UsuarioSolicita = User.Claims.FirstOrDefault(x => x.Type == System.Security.Claims.ClaimTypes.WindowsUserClaim).Value;
                _context.Add(servidoresSolicitud);
                _context.SaveChanges();
                Api api = new Api();
                string MQResp=api.Post(BC.ObtenerValor("URL:SolicitudServidoresMQ"), servidoresSolicitud);
                if (MQResp != null)
                {
                    return Redirect("/ServidoresSolicitud/Details/"+ servidoresSolicitud.GuidSolicitud);
                }
                else
                {
                    servidoresSolicitud.Mensaje = "Ha ocurrido un error con el servicio de ejecución, reporte al administrador!";
                    servidoresSolicitud.FechaHoraUltimaModificacion = DateTime.Now;
                    servidoresSolicitud.EstadoSolicitud = EstadoSolicitud.Solicitud_Error;
                    _context.Entry(servidoresSolicitud).State = EntityState.Modified;
                    _context.SaveChanges();
                    return RedirectToAction("500", "Error");
                }
            }
            return View(servidoresSolicitud);
        }

        // GET: ServidoresSolicitud/Edit/5

        // POST: ServidoresSolicitud/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        // GET: ServidoresSolicitud/Delete/5

        private bool ServidoresSolicitudExists(string id)
        {
            return _context.SolicitudesServidores.Any(e => e.GuidSolicitud == id);
        }
    }
}

LCode.InfraestruCode.Cliente/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InfraCode BCP</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="/css/mdb.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Roboto:300,400,500" rel="stylesheet">
    @await RenderSectionAsync("Css", required: false)
</head>
<body style="padding-top: 70px;">
    <header>
        <nav class="navbar fixed-top navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InfraCode BCP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    Administracion de Servidores
                                </a>
                                <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
                                    @if (User.IsInRole("Admin") || User.IsInRole("Usuario-Desarrollo"))
                                    {
                                        <a class="dropdown-item" asp-area="Desarrollo" asp-controller="ServidoresSolicitud" asp-action="Index">Servidores Desarrollo</a>
                                    }
                                    @if (User.IsInRole("Admin") || User.IsInRole("Usuario-Certificacion"))
                                    {
                                        <a class="dropdown-item" asp-controller="ServidoresSolicitud" asp-action="IndexCertificacion">Servidores Certificacion</a>
                                    }
                                    @*<a class="dropdown-item" href="#">Servidores Producción</a>*@
                                </div>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LCode.InfraCode - BCP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
        </div>
    </footer>
    <script type="text/javascript" src="../js/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <!-- Bootstrap tooltips -->
    <!-- Bootstrap core JavaScript -->
    <!-- MDB core JavaScript -->
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="../js/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="../js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="../js/mdb.min.js"></script>
    <script type="text/javascript" src="~/js/Sitio/loader.js"></script>
    <script>
        window.addEventListener('beforeunload', (event) => {
            ShowLoader();
        });
    </script>
    <script type="module">
        switch (document.readyState) {
            case "loading":
                ShowLoader();
                break;
            case "interactive":
                // The document has finished loading. We can now access the DOM elements.
                //HideLoader();
                break;
            case "complete":
                HideLoader();
                break;
        }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>